rename to prevent collisions with Python std module inspect
https://docs.python.org/3/library/inspect.html

Without renaming, running it as a script does not work:
```
python3 tensor2tensor/data_generators/inspect.py -h
Traceback (most recent call last):
  File "tensor2tensor/data_generators/inspect.py", line 31, in <module>
  ...
  File "/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py", line 20, in <module>
    import inspect as _inspect
  File "tensor2tensor/data_generators/inspect.py", line 35, in <module>
    tf.flags.DEFINE_string("subword_text_encoder_filename", "",
AttributeError: module 'tensorflow' has no attribute 'flags'
```